sudo: require
language: cpp
compiler: gcc
cache: false

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    
install:
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90

script:
    - ./build.sh
    - ./travis_gcc_gcov
    - ./get_code_cov.sh
    
after_success:
    - bash <(curl -s https://codecov.io/bash)