################################################################################
#
#                   GPP Travis CI Configuration File
#
################################################################################

sudo: require
language: cpp
compiler: gcc
cache: false

before_install:
    # C++
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    # Codecov
    - sudo pip install codecov
    
install:
    - sudo apt-get install -qq g++-6
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90

script:
    - sudo sh ./build
    - ./travis_gcc_gcov
    - sudo sh ./get_code_cov
    
after_success:
    - bash <(curl -s https://codecov.io/bash)